[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.21"
evm_version = "paris" # default is paris
optimizer = true
optimizer_runs = 200
via_ir = true

[fuzz]
runs = 1024

[rpc_endpoints]
op = "${OP_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
op = { key = "${OP_API_KEY}", chain = 10 }
goerli = { key = "${API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
